services:
  - type: web
    name: newsletter-subscription
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: "5432"
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: judekennethdost
      - key: DB_NAME
        value: newsletter_db